#!/usr/bin/env python
from urlparse import urlparse
import socket as skt
import os
import sys
import asyncore


filename = sys.argv[-2]
f = open(filename , 'wb')

servName = sys.argv[-1]
# port = 8080
parsed_url = urlparse(servName)
s = parsed_url.hostname
n = parsed_url.path
pp = parsed_url.port
if pp==None:
	pp = 80
port = pp


s = urlparse(servName).hostname
n = urlparse(servName).path
# print 'hostname',s
# print 'path', n

def sendHeader(server, path):
	return ("GET {n} HTTP/1.1\r\n"+ "Host: {s}\r\n\r\n").format(s=server, n=path)



clientSocket = skt.socket(skt.AF_INET,skt.SOCK_STREAM)
clientSocket.connect((s, port))

request1 = sendHeader(s,n)

clientSocket.send(request1)



data = ""
header_buffer = ''
bytesCount = 0
while True:

	data_received = clientSocket.recv(8192)
	header_buffer += data_received
	if '\r\n\r\n' in header_buffer:
		header, remain = header_buffer.split('\r\n\r\n')
		bytesCount += len(remain)
		f.write(remain)
		break

left_huge=''
content1 = header.split('Content-Length: ')
# print content1
ww = content1[1]
www = ww.split('Connection: ')
ContentLLL = www[0] #Content length
Cl = ContentLLL.split("\r\n")[0]
print "HHHHH "+ Cl
print "cl",type(Cl)
while bytesCount<int(Cl):
	data_received = clientSocket.recv(8192)
	# left_huge+= data_received
	f.write(data_received)
	print int(Cl) - bytesCount
	bytesCount += len(data_received)
	# if len(data_received)==0:
	# 	# f.write(left_huge)
	# 	break
 
f.close()
clientSocket.close()


# content1 = header.split('Content-Length: ')
# # print content1
# ww = content1[1]
# www = ww.split('Connection: ')
# Cl = www[0] #Content length
# print Cl

# qq = first_received.split('\r\n\r\n')
# All_data = qq[1]
# print All_data #all the remaining data

